---

- hosts: all
  become: true
  tasks:

  - name: update repositiry index
    apt:
      update_cache: yes

  - name: install apache and php for Ubuntu servers
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest