---

- hosts: all
  become: true
  tasks:

  - name: uninstall apache and php packages for Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: uninstall apache and php packages for CentOS servers
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS"