- name: install mariadb package for CentOS servers
  tags: db,maridadb,ubuntu
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package for Ubuntu servers
  tags: centos,db,maridadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"